compile:./src/main.cpp
	g++ -c ./src/main.cpp ./include/Button.cpp -o ./bin/main.o
	g++ ./bin/main.o -o ./bin/app  -I/include/headers/Button.h -lsfml-graphics -lsfml-window -lsfml-system

run:
	./bin/app